name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: main
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: sudo rm -r /home/ubuntu/uem/PCC-front/dist
    - run: sudo docker stop $(sudo docker ps -a -q)
    - run: sudo systemctl stop nginx
    - run: sudo git fetch --all
    - run: sudo git reset --hard origin/main
    - run: sudo npm ci
    - run: sudo npm run build
    - run: sudo docker rm $(sudo docker ps -a -q) && sudo docker rmi $(sudo docker images -a -q) && sudo docker build -t pcc-back /home/ubuntu/uem/PCC-back && sudo docker run -d -p 5000:5000 pcc-back
    - run: sudo systemctl start nginx
